language: android
jdk: oraclejdk8
sudo: true

notifications:
  email: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-26
    - sys-img-armeabi-v7a-android-26
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-26"
- yes | sdkmanager "build-tools;android-26"
- yes | sdkmanager "build-tools;android-27"


script:
  - ./gradlew clean assemble