language: android
jdk: oraclejdk8
sudo: true

notifications:
  email: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-26
    - sys-img-armeabi-v7a-android-26
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
- yes | sdkmanager "platforms;android-26"
